export const EMAIL_SUCCESS = "EMAIL_CONNECT_SUCCESS";
export const EMAIL_ERROR = "EMAIL_CONNECT_ERROR";
export const EMAIL_CONNECT_REQUEST = "EMAIL_CONNECT_REQUEST";
export const GET_EMAIL_CONNECT_STATUS_REQUEST = "GET_EMAIL_CONNECT_STATUS_REQUEST";
export const UPDATE_EMAIL_COPY_REQUEST = "UPDATE_EMAIL_COPY_REQUEST";
