export const EMAIL_CONNECT_REQUEST = "EMAIL_CONNECT_REQUEST";
export const EMAIL_CONNECT_SUCCESS = "EMAIL_CONNECT_SUCCESS";
export const EMAIL_CONNECT_ERROR = "EMAIL_CONNECT_ERROR";
export const GET_EMAIL_CONNECT_STATUS_REQUEST = "GET_EMAIL_CONNECT_STATUS_REQUEST";
export const GET_EMAIL_CONNECT_STATUS_SUCCESS = "GET_EMAIL_CONNECT_STATUS_SUCCESS";
export const GET_EMAIL_CONNECT_STATUS_ERROR = "GET_EMAIL_CONNECT_STATUS_ERROR";
