export const USER_CREATE = "USER_CREATE";
export const USER_VERIFY = "USER_VERIFY";
export const USER_SEND_RESET_PASSWORD_EMAIL = "USER_SEND_RESET_PASSWORD_EMAIL";
export const USER_RESET_PASSWORD = "USER_RESET_PASSWORD";
export const USER_REQUEST = "USER_REQUEST";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_ERROR = "USER_ERROR";
