// describe('Signup', () => {
//   it('clicking "type" navigates to a new url', () => {
//     cy.visit('https://app.lasso.so/signup')
//     cy.get('input[id="email"]')
//       .type('fake@email.com')
//       .should('have.value', 'fake@email.com')
//     cy.get('input[id="username"]')
//       .type('username')
//       .should('have.value', 'username')
//     cy.get('input[id="password"]')
//       .type('supersecretpassword123%%')
//       .should('have.value', 'supersecretpassword123%%')
//     cy.contains('Sign Up').click()
//     // cy.get('notification')
//     //   .should('contain', 'Account verification email sent! Please check your inbox.')
//   })
// })
